GET http://localhost:3000/messages

### create a new message
POST http://localhost:3000/messages

content-type: application/json 

{
    "content": "aaahi there"
}
### get a message
GET http://localhost:3000/messages/333